name: test dispatch

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of the Release year_week# example : 2019.50'
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest
    name: create_release
    steps:
    - uses: actions/checkout@v2
    - id: foo
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.event.inputs.release_name }}
        release_name: Release ${{ github.event.inputs.release_name }}
        body_path: ${{github.workspace}}/RELEASE.md
        draft: false
        prerelease: false
